### ISSUE TITLE
How to keep iphone ios xmpp connection alive while in the background?

### ISSUE THREAD

**Issue by swathi-gali** [robbiehanson/XMPPFramework#52]
Xmpp gets disconnected automatically if the app is in the background for more than 3-4 minutes. Is there anyway to keep the connection alive indefinitely or atleast for 30minutes or so?

**Comment by guptatarun84** [comment]
Please share how you did it?

**Comment by parthpatel1105** [comment]
It is not working for me by using enableBackgroundingOnSocket. Please help me. I am stuck.

**Comment by guptatarun84** [comment]
You need an push notification once the user is offline to enable app which is in background and immediately make an connect request to XMPP to get the app alive from background. In my case I used the same mechanism.

**Comment by Amitmundra** [comment]
If app in background and when we take the app in foreground after 30 minutes then it autoreconnect event doesn't fire, Should XMPP library do this or should we do something else to make connect automatically?

Thanks.

**Comment by guptatarun84** [comment]
Auto reconnect only happens when there is network issue. Incase you need application to wake up from background mode you need to enable push notification through which the application would become active and send a connect request within 30 secs of the whole procedure. Although this is not a full proof solution due to restriction provided by Apple however will work.

**Comment by Amitmundra** [comment]
Thanks, Anything else that i can do to keep active connection in BG as well?

**Comment by guptatarun84** [comment]
Use iOS default background modes enabled if you have no restrictions with respect to your app requirements :)
