### ISSUE TITLE
Carbon messages are not received in ios

### ISSUE THREAD

**Issue by vijayaa** [robbiehanson/XMPPFramework#769]
We are using following code for enabling carbon messages

` XMPPMessageCarbons *xmppMessageCarbon  = [[XMPPMessageCarbons alloc] initWithDispatchQueue:dispatch_get_main_queue()];

[xmppMessageCarbon activate:xmppStream];
[xmppMessageCarbon enableMessageCarbons]; `

But carbon messages are not received

**Comment by vitalyster** [comment]
You need to have a class conforming `XMPPMessageCarbonsDelegate` protocol and add it delegates of `XMPPMessageCarbons` instance

**Comment by andresinaka** [comment]
hey @vijayaa, here you have the definition of the XMPPMessageCarbonsDelegate. As @vitalyster said you have to have a class conforming this protocol and remember to add the delegate to the message carbons module:

`[xmppMessageCarbon addDelegate:self delegateQueue:your_queue];`

```
@protocol XMPPMessageCarbonsDelegate <NSObject>

- (void)xmppMessageCarbons:(XMPPMessageCarbons *)xmppMessageCarbons willReceiveMessage:(XMPPMessage *)message outgoing:(BOOL)isOutgoing;

- (void)xmppMessageCarbons:(XMPPMessageCarbons *)xmppMessageCarbons didReceiveMessage:(XMPPMessage *)message outgoing:(BOOL)isOutgoing;

@end
```

**Comment by vijayaa** [comment]
After adding this change also it is not working. As per XEP-0280 client should send request to server with  iq
<enable xmlns="urn:xmpp:carbons:2"/> . So that server will enable carbon for that user. But client is not sending this iq to server

**Comment by vitalyster** [comment]
@vijayaa are you sure you have support on the server side and it is enabled?

**Comment by vijayaa** [comment]
Yes  server has that support. In android it is working

**Comment by techwizardg** [comment]
Any update on the same? Though enable carbons is called iq message is not sent to server from iOS App

**Comment by andresinaka** [comment]
@vijayaa @techwizardg you will have to start debugging to see where the problem is... If I were you I would start with a breakpoint in the `activate` of the `XMPPMessageCarbons` and would also add an other in the `deactivate` to be sure nobody is calling it...

Then add two more breakpoints in:
```
- (void)xmppStream:(XMPPStream *)sender didReceiveMessage:(XMPPMessage *)message
- (XMPPMessage *)xmppStream:(XMPPStream *)sender willReceiveMessage:(XMPPMessage *)message
```

Those two have to be called everytime a message is received... so start with this... and let's see how it goes...

**Comment by rikoap** [comment]
@vijayaa Have you solve your problem?

XMPPMessageCarbons works on my app.
To enable message carbon, set property `autoEnableMessageCarbons` to `true`. 
If you use `enableMessageCarbons` method, you should call it after authenticated.

**Comment by vijayaa** [comment]
Yes it is solved for me also

**Comment by sohanshrooms** [comment]
I am getting message in `func xmppMessageCarbons(_ xmppMessageCarbons: XMPPMessageCarbons, didReceive message: XMPPMessage, outgoing isOutgoing: Bool) {` while sending message from different client, But I don't know how to save that message in `XMPPRosterCoreDataStorage`  so that Whenever user open the app I can get history from the `XMPPRosterCoreDataStorage` .
