### ISSUE TITLE
Doesn't work XMPP connection in the background in iOS10

### ISSUE THREAD

**Issue by x3mall1986** [robbiehanson/XMPPFramework#807]
In iOS 9 all worked fine, after updating to iOS10, account becomes offline after the lock screen on iPhone.

`self.xmppStream.enableBackgroundingOnSocket = YES;`

<img width="982" alt="2016-09-23 17 27 41" src="https://cloud.githubusercontent.com/assets/1582648/18789280/18f46c14-81b3-11e6-949e-8b9d22395109.png">

**Comment by chrisballinger** [comment]
VoIP background sockets are no longer supported by Apple. You have to use
PushKit now.

**Comment by x3mall1986** [comment]
it will return the opportunity to stay a contact online in background?

**Comment by duxiaoyan** [comment]
I've had the same problem，Kindly give us your advice，Tanks

**Comment by kashankhan** [comment]
You have to use  PushKit https://developer.apple.com/reference/pushkit. Framework introduce by apple to avoid background socket. Following is the link of tutorial.
http://pierremarcairoldi.com/ios-8-voip-notifications/
You can use same APNS implementing of server the only change instead of provide APNS certificate you have to use VOIP certificate.

**Comment by davidah3** [comment]
Actually there is not way to work in background in iOS 10 like before. I'm using the way that @kashankhan did explain in his answer and work perfectly. 

Another solution is using a Background Task when receive a Push Notification but this just have a period of time to work in background.

**Comment by vdonoso007** [comment]
Hello kashankhan, davidah3 

Please help me, I followed your advance about like xmpp works on background mode with voIP, but it's not working... What else to need be so that this work. Please help me, I am frustrated because I must deliver this urgently for my work.

Best regards!!!

**Comment by davidah3** [comment]
@vdonoso007 What are you trying to do exactly in background?

**Comment by adozenlines** [comment]
Apple doesn't support long running background task but if you can introduce a loop in your background task you can give it a try an rick rejection if the application is not a true VoIP app.

**Comment by vdonoso007** [comment]
I have tried to execute the following, but after 3 minutes the connection is closed. Then removed these code: UIApplication*    app = [UIApplication sharedApplication];
    bgTask = [app beginBackgroundTaskWithExpirationHandler:^{
        [app endBackgroundTask:bgTask];
        bgTask = UIBackgroundTaskInvalid;
    }];
    // Start the long-running task and return immediately.
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        
        NSTimer *t = [NSTimer scheduledTimerWithTimeInterval:10 target:self selector:@selector(connect) userInfo:nil repeats:YES];
        [[NSRunLoop currentRunLoop] addTimer:t forMode:NSDefaultRunLoopMode];
        [[NSRunLoop currentRunLoop] run];
        
    });

**Comment by adozenlines** [comment]
Yup follow the suggestions for using pushkit as the old methods no longer work.

**Comment by vdonoso007** [comment]
Clear, it mean that the user xmpp always will keep offline him until that server can to send a push notification to user? if this is thus, how to send a notification push to user from openfire server, since I currently have a service that is responsible for sending a chat type message to the client.

On the other hand, because there are IM clients that are kept connected to the openfire server being in the background eg astrachat ...

**Comment by chrisballinger** [comment]
Look at XEP-0357.

**Comment by davidah3** [comment]
The app will stay "awake" for 3 minutes every time that you minimize the app, then every time that the app receive a "voip" push notification (not a normal push notification) (PushKit) the app will "wake up" for 30 seconds, in these 30 seconds you need to reconnect your XMPPStream and download all the pending messages, after 25 seconds you should ensure to disconnect the XMPPStream just for avoid some kind of issue.

**Comment by vdonoso007** [comment]
From what I understand, I can not wake up the app without voip push notification ?, I ask this because when downloading the pending messages as indicated by reconnecting the xmppstream, I have a push type message that is not the chat message I send from the service Java, this is so? Or I have to do not to present the voip push notification, please your help I am very desperate with this, thank you very much for your time and attention

**Comment by hpDeviOS** [comment]
Hello,

One of my app with XMPP, has been rejected due to Using VoIP in app.
Purpose of using PushKit(VoIP) is to connect app when its Force killed/background, to send deliver of received messages.

Any suggestion which will full fill requirement and also won't Reject from Apple.

Thanks in Advance!!!

**Below From Apple (unresolved iOS issue)**
Guideline 2.5.4 - Performance - Software Requirements

Your app declares support for VoIP in the UIBackgroundModes key in your Info.plist, but it does not include any Voice over IP services.

Next Steps

To resolve this issue, please revise your app to either add VoIP features or remove the "voip" setting from the UIBackgroundModes key.

We recognize that VoIP can provide "keep alive" functionality that is useful for many app features. However, using VoIP in this manner is not the intended purpose of VoIP.


Since your App Store Connect status is Metadata Rejected, we do NOT require a new binary. To revise the metadata, visit App Store Connect to select your app and revise the desired metadata values. Once you’ve completed all changes, reply to this message in Resolution Center and we will continue the review.

**Comment by davidah3** [comment]
PushKit is designed for VoIP apps, I mean is used for wake up the app and receive calls. I know that have a lot of advantages for common applications but is so restricted by Apple. 
https://developer.apple.com/documentation/pushkit
https://developer.apple.com/documentation/pushkit/pkpushregistry
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html

You can implement some easy VoIP feature in your app like:
https://github.com/jitsi/jitsi-meet-ios-sdk-releases
or make your own implementation for audio-calls or video-calls.

Note: Apple will request to you evidence in case that they can not access to the VoIP feature.

Regards.

**Comment by shivangpandya9** [comment]
Hello , 
Same problem happened with me that can't get any method to keep connection alive or get message notification if user terminate application/background mode. 
If anyone find any solution then please reply or guide me , it would be great help for me. 
Thanks in advance.

**Comment by muisawe** [comment]
> Hello ,
> Same problem happened with me that can't get any method to keep connection alive or get message notification if user terminate application/background mode.
> If anyone find any solution then please reply or guide me , it would be great help for me.
> Thanks in advance.

did you get any help ?
