### ISSUE TITLE
Latest release tag v3.6.5 is way outdated

### ISSUE THREAD

**Issue by dodikk** [robbiehanson/XMPPFramework#869]
```
@ObjColumnist ObjColumnist released this on Aug 6, 2015 · 146 commits to master since this release
```

As far as I can see, the changes have been solid enough :

* There are massive changes in terms of dependency management : the "vendor" directory has been removed completely.
* Some `XEP` extensions have been added

Isn't it the right time for a new version?

**Comment by dodikk** [comment]
I'm going to reference `XMPPFramework` using Carthage and specifying no version feels bad.
Specifying a commit is somewhat better but still not quite elegant.

**Comment by chrisballinger** [comment]
@dodikk I was planning on putting out a 3.7.0 release soon, it's a time consuming process though. I see you added Carthage support to KissXML, were you planning on making a similar PR for XMPPFramework?

**Comment by dodikk** [comment]
>> I see you added Carthage support to KissXML, were you planning on making a similar PR for XMPPFramework?

Yes, I am if I can do that. A bit harder than I expected ((
I'm working at it.
I'm going to add core classes support. XEP extensions might be an issue

**Comment by chrisballinger** [comment]
I think we need to consider an alternative way to determine module availability, instead of using the `#ifdef` and customizable `XMPPFramework.h` as before. The podspec never worked properly with that, so I had to remove it and just bundle all modules in the `XMPPFramework.h` header. The podspec was also impossible to publish because it forces you to lint ~30 subspecs for macOS/iOS/x86/x86_64/armv7/arm64.

**Comment by dodikk** [comment]
Carthage support pull request https://github.com/robbiehanson/XMPPFramework/pull/870

```
Warning: it's incomplete yet
```

**Comment by chrisballinger** [comment]
3.7.0 tag is out
