### ISSUE TITLE
Can I use this framework in iOS 7.0?

### ISSUE THREAD

**Issue by Don4iOS** [robbiehanson/XMPPFramework#896]
The README.md file shows that the minimum deployment target is iOS 8.0. How can I use this framework in iOS 7.0? 

Thank you for your help!

**Comment by vitalyster** [comment]
"Minimum deployment target" mentioned for Cocoapods/Carthage installations (as they only support dynamic frameworks). You can just use include XMPPFramework files directly in your project and it mostly should work on older iOS versions

**Comment by vitalyster** [comment]
In fact, Cocoapods may link statically, but as I understand, project developers doesn't want to waste time to fix issues for platforms that have less than 1% of global usage stats.

**Comment by chrisballinger** [comment]
There is absolutely no reason to support iOS 7 in 2017. If anything you should consider moving your minimum target to iOS 9 because that still includes all devices manufactured since 2011 and will reduce your support burden. You can't even test iOS 7 anymore, and the iOS 8 simulator will be removed in a few months when iOS 11 comes out.

**Comment by Don4iOS** [comment]
@vitalyster @chrisballinger Thank you for your answer answers!

**Comment by Don4iOS** [comment]
@vitalyster @chrisballinger By the way, which is the lastes version supports iOS 7.0+? I have to support iOS 7.0+ in my project. Thank you!

**Comment by chrisballinger** [comment]
Older versions of XMPPFramework are unsupported and I do not recommend using them. Apple stopped signing iOS 7 in 2014, and every device released since 2011 supports iOS 9 or higher.

Does your project manager have a good reason for requiring iOS 7? If not, you should push back because targeting obsolete unsupported iOS versions will only increase developer cost and reduce the quality of the end product.

**Comment by Don4iOS** [comment]
OK, thanks for your good advice. I will push back this requirement.
